### ISSUE TITLE
Add monthly precipitation in Excel format

### ISSUE THREAD

**Issue by monocongo** [monocongo/example_climate_indices#3]
For use as input for a Jupyter notebook proposed in [this issue](https://github.com/monocongo/climate_indices/issues/311).

**Comment by pankajkarman** [comment]
Thanks, @monocongo. I am attaching the monthly rainfall dataset in excel. 
[Monthly_Seasonal_Data_Corrected_Version.xlsx](https://github.com/monocongo/example_climate_indices/files/3159065/Monthly_Seasonal_Data_Corrected_Version.xlsx)
The details are as follows:
Station: Dharmanagar, India [ 24.37° N, 92.15° E ].
Elevation: 21m (69 ft).
As far as the attribution is concerned, my name is Pankaj Kumar and I am a PhD student at Indian Institute of Technology Kharagpur, India.

**Comment by monocongo** [comment]
Resolved by PRs #4 and #5
