### ISSUE TITLE
I struggle to install the latest version 1.0.9

### ISSUE THREAD

**Issue by greenfrog203** [monocongo/example_climate_indices#6]
[install_climate-indices.txt](https://github.com/monocongo/example_climate_indices/files/4296111/install_climate-indices.txt)

Hello everybody
I am totally new to programming and now want to use climate-indices to calculate SPI and SPEI.
I finally configured the Python environment at it is described in the documentation (https://climate-indices.readthedocs.io/en/latest/) but my environment installed version 1.0.8 instead of 1.0.9.
I use Anaconda3 on Linux.
I tried first  "pip3 install climate-indices" and after uninstalling I tried second the standard installation command "pip install climate-indices" but both downloaded and installed version 1.0.8.
Unfortunately I did'nt copy the first attempt, but I provided the code for uninstalling and second installing in the attached .txt-file. (Think the package was not really uninstalled...you will see in the code).
I hope anybody can help me.
Thanks in advance!

**Comment by monocongo** [comment]
I'm unsure of why this is happening, as the installation from PyPI should provide the latest version (1.0.9).

I suggest starting over by creating a new conda environment:
```
$ conda create -n climate python=3 --yes
$ conda activate climate
(climate) $ pip install climate-indices
(climate) $ conda list climate-indices
# packages in environment at /home/james/miniconda3/envs/climate:
#
# Name                    Version                   Build  Channel
climate-indices           1.0.9                    pypi_0    pypi
```

(BTW this should actually be an issue in the [climate_indices](https://github.com/monocongo/climate_indices) project)

**Comment by greenfrog203** [comment]
This worked out! Thanks a lot! 
Sorry, I missed that I was in the wrong project.

**Comment by monocongo** [comment]
Great news! Thanks for the follow up, @greenfrog203
